include ~/.cache/wal/colors-kitty.conf
include ~/.cache/wal/colors-kitty-tabs.conf

font_size 14.0
font_family FantasqueSansM Nerd Font

# TABS
tab_bar_min_tabs            0
tab_bar_edge                bottom
tab_bar_style               separator
tab_bar_min_tabs 2
tab_title_template " {title} "
tab_separator " "

# ADVANCED
shell_integration           enabled
allow_remote_control        yes
listen_on                   unix:/tmp/mykitty
editor                      nvim

# Permet d'ouvrir les URLs cliquables
allow_hyperlinks yes
# Souligne les hyperliens (OSC 8) toujours
underline_hyperlinks always
# Style de soulignage des URLs (none/straight/double/curly/dotted/dashed)
url_style straight
# Détecte les URLs automatiquement
detect_urls yes
# Couleur des URLs détectées
url_color #0087BD

# MISC
enable_audio_bell no

disable_ligatures never
text_composition default

cursor_trail 1

# MAPS
map ctrl+shift+r load_config_file
