include ~/.cache/wal/colors-kitty.conf
include ~/.cache/wal/colors-kitty-tabs.conf

font_size 14.0
font_family FantasqueSansMono Nerd Font Mono

# TABS
tab_bar_min_tabs            0
tab_bar_edge                bottom
tab_bar_style               separator
tab_bar_min_tabs 2
tab_title_template " {title} "
tab_separator " "

# ADVANCED
shell_integration           enabled
allow_remote_control        yes
listen_on                   unix:/tmp/mykitty
editor                      nvim

# MISC
allow_hyperlinks yes
enable_audio_bell no

disable_ligatures never

# MAPS
map ctrl+shift+r load_config_file
